#!/bin/bash
# LENS Workbench v2.0.0 - Audience Promotion PR Creation Script
# =============================================================================
# Creates pull requests for audience promotion gates
# Usage: ./create-promotion-pr.sh small medium
# =============================================================================

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Parse arguments
SOURCE_AUDIENCE=$1
TARGET_AUDIENCE=$2
INITIATIVE_ROOT=$3
DRY_RUN=${4:-false}

# Functions
error() { echo -e "${RED}✗ $1${NC}" >&2; exit 1; }
success() { echo -e "${GREEN}✓ $1${NC}"; }
info() { echo -e "${CYAN}$1${NC}"; }
warning() { echo -e "${YELLOW}⚠ $1${NC}"; }

# Header
info "======================================"
info "LENS Workbench Audience Promotion"
info "======================================"

# Validate arguments
if [[ -z "$SOURCE_AUDIENCE" || -z "$TARGET_AUDIENCE" ]]; then
    error "Usage: $0 <source_audience> <target_audience> [initiative_root] [dry_run]"
fi

# Validate promotion path
case "$SOURCE_AUDIENCE-$TARGET_AUDIENCE" in
    "small-medium"|"medium-large"|"large-base")
        success "Valid promotion: $SOURCE_AUDIENCE → $TARGET_AUDIENCE"
        ;;
    *)
        error "Invalid promotion path: $SOURCE_AUDIENCE → $TARGET_AUDIENCE\nValid: small→medium, medium→large, large→base"
        ;;
esac

# Get initiative root from state if not provided
if [[ -z "$INITIATIVE_ROOT" ]]; then
    STATE_FILE="_bmad-output/lens-work/state.yaml"
    if [[ -f "$STATE_FILE" ]]; then
        INITIATIVE_ROOT=$(grep "active_initiative:" "$STATE_FILE" | awk '{print $2}')
        if [[ -z "$INITIATIVE_ROOT" || "$INITIATIVE_ROOT" == "null" ]]; then
            error "No active initiative found in state.yaml"
        fi
        info "Using initiative: $INITIATIVE_ROOT"
    else
        error "State file not found: $STATE_FILE"
    fi
fi

# Set gate information based on promotion type
case "$SOURCE_AUDIENCE-$TARGET_AUDIENCE" in
    "small-medium")
        GATE="adversarial-review"
        TITLE="🔍 Adversarial Review Gate: Small → Medium"
        DESC="Party mode review complete. All small-audience phases ready for lead review."
        ;;
    "medium-large")
        GATE="stakeholder-approval"
        TITLE="👥 Stakeholder Approval Gate: Medium → Large"
        DESC="DevProposal phase complete. Epics and stories ready for stakeholder review."
        ;;
    "large-base")
        GATE="constitution-gate"
        TITLE="📋 Constitution Gate: Large → Base"
        DESC="SprintPlan complete. Ready for development execution."
        ;;
esac

# Build branch names
SOURCE_BRANCH="$INITIATIVE_ROOT-$SOURCE_AUDIENCE"
if [[ "$TARGET_AUDIENCE" == "base" ]]; then
    TARGET_BRANCH="$INITIATIVE_ROOT"
else
    TARGET_BRANCH="$INITIATIVE_ROOT-$TARGET_AUDIENCE"
fi

info "\nPromotion Details:"
info "  Gate: $GATE"
info "  Source: $SOURCE_BRANCH"
info "  Target: $TARGET_BRANCH"

if [[ "$DRY_RUN" == "true" ]]; then
    warning "\n[DRY RUN MODE - No changes will be made]"
fi

# Verify source branch exists
if ! git rev-parse --verify "$SOURCE_BRANCH" >/dev/null 2>&1; then
    error "Source branch not found: $SOURCE_BRANCH"
fi
success "Source branch exists"

# Create target branch if needed
if ! git rev-parse --verify "$TARGET_BRANCH" >/dev/null 2>&1; then
    if [[ "$DRY_RUN" != "true" ]]; then
        info "Creating target branch: $TARGET_BRANCH"
        if [[ "$TARGET_AUDIENCE" == "base" ]]; then
            git checkout -b "$TARGET_BRANCH" "$SOURCE_BRANCH"
        else
            git checkout -b "$TARGET_BRANCH"
        fi
        git push -u origin "$TARGET_BRANCH"
    else
        warning "[DRY RUN] Would create branch: $TARGET_BRANCH"
    fi
fi
success "Target branch ready"

# Generate PR body
PR_BODY="## $DESC

This pull request represents the **$GATE** for audience promotion from \`$SOURCE_AUDIENCE\` to \`$TARGET_AUDIENCE\`.

---

### 📋 Promotion Checklist

- [ ] All $SOURCE_AUDIENCE-audience phases complete
- [ ] Required artifacts present and validated
- [ ] Gate requirements satisfied
- [ ] Team approval received

---

### 🎯 Audience Progression

\`\`\`
small → [adversarial-review] → medium → [stakeholder-approval] → large → [constitution-gate] → base
      ↑                              ↑                                ↑
      $([ "$SOURCE_AUDIENCE" == "small" ] && echo "YOU ARE HERE" || echo "            ")                            $([ "$SOURCE_AUDIENCE" == "medium" ] && echo "YOU ARE HERE" || echo "            ")                              $([ "$SOURCE_AUDIENCE" == "large" ] && echo "YOU ARE HERE" || echo "            ")
\`\`\`

---

### 📁 Changes Summary

\`\`\`bash
git diff $TARGET_BRANCH...$SOURCE_BRANCH --stat
\`\`\`

---

### ⚙️ Lifecycle v2 Information

- **Initiative:** \`$INITIATIVE_ROOT\`
- **Promotion Type:** \`$GATE\`
- **Source Audience:** \`$SOURCE_AUDIENCE\`
- **Target Audience:** \`$TARGET_AUDIENCE\`

---

_Generated by LENS Workbench v2.0.0_"

# Create the PR
if [[ "$DRY_RUN" != "true" ]]; then
    info "\nCreating pull request..."

    # Push current branch
    git push origin "$SOURCE_BRANCH"

    # Create PR using gh CLI
    gh pr create \
        --title "$TITLE" \
        --body "$PR_BODY" \
        --base "$TARGET_BRANCH" \
        --head "$SOURCE_BRANCH" \
        --label "lens-promotion,$GATE" \
        --assignee "@me"

    if [[ $? -eq 0 ]]; then
        success "\n✅ Pull request created successfully!"
        success "View your PR: gh pr view --web"
    else
        error "Failed to create pull request"
    fi
else
    warning "\n[DRY RUN] Would create PR:"
    info "  Title: $TITLE"
    info "  Base: $TARGET_BRANCH"
    info "  Head: $SOURCE_BRANCH"
    echo -e "\nPR Body Preview:\n$PR_BODY"
fi

info "\n======================================"
success "Promotion PR script complete!"
info "======================================"